export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_CART_TOTAL = "SET_CART_TOTAL";
export const SET_CART_COUNT_ITEMS = "SET_CART_COUNT_ITEMS";
export const SET_FAVOURITE_COUNT_ITEMS = "SET_FAVOURITE_COUNT_ITEMS";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_CART_ID = "SET_CART_ID";
export const SET_CHECKOUT_TOKEN = "SET_CHECKOUT_TOKEN";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_CHECKOUT_TOKEN_SUCCESS = "SET_CHECKOUT_TOKEN_SUCCESS";
export const SET_USER_DETAIL_SUCCESS = "SET_USER_DETAIL_SUCCESS";
export const SET_CHECKOUT_STEP = "SET_CHECKOUT_STEP";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_LATEST_PRODUCTS = 'SET_LATEST_PRODUCTS';
export const SET_FILTERATION = "SET_FILTERATION";
export const SET_CATEGORIES = "SET_CATEGRIES";
export const SET_CATEGORIES_TOAST = "SET_CATEGORIES_TOAST"
export const SET_FAVOURITES = "SET_FAVOURITES";

export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_ON_UPDATE = "SET_LOADING_ON_UPDATE";
export const SET_LOADING_ON_CLEAR_CART = "SET_LOADING_ON_CLEAR_CART";
export const SET_LOADING_ON_CHECKOUT_CART = "SET_LOADING_ON_CHECKOUT_CART";
export const SET_LOADING_ON_PAGE_CHANGE = "SET_LOADING_ON_PAGE_CHANGE";
export const SET_TOAST = "SET_TOAST";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SORT_QUERY = "SET_SORT_QUERY";